# Generated by Django 3.2 on 2021-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_homepagemodel_movie_page_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='page_view',
            field=models.IntegerField(default=1),
        ),
    ]
