# Generated by Django 3.2 on 2021-11-25 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_episode_season_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='serial',
        ),
        migrations.AddField(
            model_name='episode',
            name='download_link1080',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='download_link480',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='download_link720',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='season_name',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
