# Generated by Django 3.2 on 2021-11-27 19:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20211127_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_number', models.CharField(default='1', max_length=50)),
                ('download_link1080', models.CharField(blank=True, max_length=650, null=True)),
                ('download_link720', models.CharField(blank=True, max_length=650, null=True)),
                ('download_link480', models.CharField(blank=True, max_length=650, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_name', models.CharField(default='1', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('Serial_name', models.CharField(max_length=200)),
                ('release_date', models.CharField(default='None', max_length=70)),
                ('short_intro', models.TextField(max_length=700)),
                ('IMDb_RATING', models.CharField(default=None, max_length=50)),
                ('poster', models.ImageField(upload_to='Posters/')),
                ('serie_page_poster', models.ImageField(blank=True, null=True, upload_to='Posters/SerialPage/')),
                ('summary', models.TextField(max_length=1600)),
                ('trailer', models.CharField(blank=True, max_length=650, null=True)),
                ('page_view', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.director')),
                ('episodes', models.ManyToManyField(default=None, to='Home.Episode')),
                ('genre', models.ManyToManyField(to='Home.Genre')),
                ('seasons', models.ManyToManyField(default=None, to='Home.Season')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
