# Generated by Django 3.2 on 2021-11-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20211127_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='chose_season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.season'),
        ),
    ]
