# Generated by Django 3.2 on 2021-11-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_episode_chose_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='serie_page_poster',
            new_name='seriel_page_poster',
        ),
    ]
