# Generated by Django 3.2 on 2021-11-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_rename_serie_page_poster_serial_seriel_page_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='Episodes',
            field=models.ManyToManyField(default=None, to='Home.Episode'),
        ),
    ]
