# Generated by Django 3.2 on 2021-11-29 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_season_episodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, max_length=650, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='chose_season',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='Episodes',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Home.Episode'),
        ),
    ]
