# Generated by Django 3.2 on 2021-11-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20211129_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='movie_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.homepagemodel'),
        ),
    ]
