# Generated by Django 3.2 on 2021-11-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_comments_movie_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='movie_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Home.homepagemodel'),
        ),
    ]
