# Generated by Django 3.2 on 2021-11-30 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_comments_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments_serial',
            fields=[
                ('name', models.CharField(default='Guest', max_length=200)),
                ('body', models.TextField(blank=True, max_length=650, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('movie_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.serial')),
            ],
        ),
    ]
