# Generated by Django 3.2 on 2021-11-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_comments_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_serial',
            name='movie_page',
        ),
        migrations.AddField(
            model_name='comments_serial',
            name='serial_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_serial', to='Home.serial'),
        ),
    ]
